config/routes.rb
Expomobile::Application.routes.draw do

  resources :massive_loads

  resources :system_configurations

  get "rating/show_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  resources :exhibitors
  
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"

  devise_for :users

  resources :users

  devise_scope :user do
    get "devise/sessions/sing_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_user
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  attr_accessible :name, :workshop_key, :room_id, :teacher_name
  belongs_to :room
  has_many :schedules
  has_many :subgroups, :through => :schedules
  has_many :hours, :through => :schedules
  
  validates :name, :workshop_key, :room_id, :teacher_name, :presence => true
  validates :room_id, :uniqueness => true
  before_destroy :workshop_with_subgroups?
  
  private
  
  def workshop_with_subgroups?
    return subgroups.blank?
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  def index
    @workshops = Workshop.order('id DESC').paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @workshops }
    end
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/new
  # GET /workshops/new.json
  def new
    @workshop = Workshop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/1/edit
  def edit
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(params[:workshop])

    while @workshop.workshop_key.nil?
      random_value = Array.new(3) {[*'0'..'9', *'a'..'z'].sample}.join
      @exists = Workshop.find_by_workshop_key(random_value) || Exhibitor.find_by_exposition_key(random_value)
        
      if @exists.nil?
        @workshop.workshop_key = random_value
      end
    end

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: t(:successfully_created) }
        format.json { render json: @workshop, status: :created, location: @workshop }
      else
        format.html { render action: "new" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workshops/1
  # PUT /workshops/1.json
  def update
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      if @workshop.update_attributes(params[:workshop])
        format.html { redirect_to @workshop, notice: t(:successfully_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop = Workshop.find(params[:id])
    @deleted = @workshop.destroy
    p @deleted
    sleep 3
    flash[:error] = t("workshop.workshop_cant_be_destroyed") if !@deleted

    respond_to do |format|
      format.html { redirect_to workshops_url }
      format.json { head :no_content }
    end
  end
  
  def set_tolerance
    if !params[:tolerance].blank?
      if SystemConfiguration.first.update_attributes(workshop_tolerance: params[:tolerance])
        flash[:notice] = t(:tolerance_set_successfully)
      else
        flash[:error] = t(:tolerance_not_set)
      end
    end
    redirect_to workshops_path
  end
  
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "workshops" %>
<% end %>

<%= render "layouts/first_tab" %>
<%= form_for(@workshop) do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <% if @workshop.errors.count == 1 %>
        <h2><%= t('activerecord.errors.template.header.one', :model => t("activerecord.models.workshop")) %></h2>
      <% else %>
        <h2><%= t('activerecord.errors.template.header.other', :model => t("activerecord.models.workshop"), :count => @workshop.errors.count) %></h2>
      <% end %>
      <ul>
        <% @workshop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="field">
    <%= f.label t("workshop.name") %>
    <%= f.text_field :name, :class=>"text-input small-input", :required => true %><span class="required">*</span>
  </p>
  <% if action_name == "edit" || action_name == "update" %>
    <p class="field">
      <%= f.label t("workshop.workshop_key") %>
    <h4><%= @workshop.workshop_key %></h4>
    </p>
  <% end %>
  <p class="field">
    <%= f.label t("workshop.teacher_name") %>
    <%= f.text_field :teacher_name, :class=>"text-input small-input", :required => true %><span class="required">*</span>
  </p>
  <p class="field">
    <%= f.label t("workshop.room") %>
    <%= f.collection_select :room_id, Room.order(:name), :id ,:name %>
  </p>
  <br/><br/>
  <div class="form-actions">
    <%= f.submit nil, :class => 'button' %>
  </div>

<% end %>

app/views/workshops/index.html.erb
<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
  <table>
    <thead>
      <tr>
        <%#*<th><input class="check-all" type="checkbox" /></th>%>
        <th><%= t'.id' %></th>
                  <th><%= t'workshop.name' %></th>
                  <th><%= t'workshop.workshop_key' %></th>
                  <th><%= t'workshop.teacher_name' %></th>
                  <th><%= t'workshop.room' %></th>
              </tr>

    </thead>

    <tfoot>
      <tr>
        <td colspan="8">
          <%#*<div class="bulk-actions align-left">%>
            <%#= render "layouts/select_action" %>
          <%#*</div>%>
          <%= render "layouts/pagination" %>
          <div class="clear"></div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @workshops.each do |workshop| %>
      <tr>
        <%#*<td><input type="checkbox" /></td>%>
        <%#if can? :show, Workshop %>
        <%#*<td><%=link_to workshop.id, workshop, :class => 'button'</td>%>
        <%#else%>
        <td><%= label workshop.id, workshop.id %></td>
        <%#end%>
                
             <% @model = workshop %>
                          
          <td><%= workshop.name %></td>
          
          <td><%= workshop.workshop_key %><br/><%= link_to t(:qr_code), qr_generator_generate_qr_path(:key => workshop.workshop_key, :workshop_name => workshop.name, :teacher_name => workshop.teacher_name, :room => workshop.room.name), :class => "qr_code" %></td>
                             
          <td><%= workshop.teacher_name %></td>
                             
          <td><%= workshop.room.name %></td>
                <%= render "layouts/index_links" %>
        <% end %>
    </tbody>
  </table>
  <%= form_tag workshops_set_tolerance_path, :id => "tolerance_form", method: :post do %>
    <%= label_tag t(:set_tolerance) %>
    <%= text_field_tag "tolerance", SystemConfiguration.first.workshop_tolerance, :class=>"text-input small-input", :style => "width: 10% !important;" %>
    <%= submit_tag t(:accept), :class => 'button' %>
  <% end %>
  <%= render "layouts/action_links" %>
</div> 
<%= render "layouts/second_tab" %>

app/views/workshops/show.html.erb
<%= render "layouts/first_tab" %>

<div class="CSSTableGenerator" >
  <table >
          <tr>
        <td>
          <b><%= @workshop.name.upcase %>
        </td>
      </tr>
          <tr>
        <td>
          <b><%= t'workshop.workshop_key' %>:<%= @workshop.workshop_key %><br/><%= link_to t(:qr_code), qr_generator_generate_qr_path(:type => "workshop", :key => @workshop.workshop_key), :class => "qr_code" %>
        </td>
      </tr>
          <tr>
        <td>
          <b><%= t'workshop.teacher_name' %>:<%= @workshop.teacher_name %>
        </td>
      </tr>
          <tr>
        <td>
          <b><%= t'workshop.room' %>:<%= @workshop.room.name %>
        </td>
      </tr>
      </table>
</div>


<%= render "layouts/action_links" %>