config/routes.rb
Expomobile::Application.routes.draw do

  resources :massive_loads

  resources :system_configurations

  get "rating/show_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  resources :exhibitors
  
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"

  devise_for :users

  resources :users

  devise_scope :user do
    get "devise/sessions/sing_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_user
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :authenticate_user!

  def visits_to_workshops_by_workshop
    if params[:subgroup_id] =~ /\A\d+\z/
      @subgroup_id = params[:subgroup_id]
    end
  end
  
  def visits_to_workshops
    @attendees = []
    @subgroups = {}
    if params[:workshop_id] =~ /\A\d+\z/ && params[:subgroup_id].blank?
      @attendees = Attendee.joins("INNER JOIN attendee_workshops a ON attendees.id = a.attendee_id")
      .where("a.workshop_id = ?", params[:workshop_id])
    elsif params[:workshop_id] =~ /\A\d+\z/ && params[:subgroup_id] =~ /\A\d+\z/
      @attendees = Attendee.joins("INNER JOIN subgroups s ON attendees.subgroup_id = s.id")
      .joins("INNER JOIN attendee_workshops a ON attendees.id = a.attendee_id")
      .where("attendees.subgroup_id = ? AND a.workshop_id = ?", params[:subgroup_id], params[:workshop_id])
    end
    @attendees.each do |a|
      a[:register_date] = AttendeeWorkshop.find_by_attendee_id_and_workshop_id(a.id, params[:workshop_id]).created_at
      subgroup_name = a.subgroup.name
      if @subgroups.has_key?(subgroup_name)
        @subgroups[subgroup_name] << a
      else
        @subgroups[subgroup_name] = [a]
      end
    end
  end
  
  def visits_to_workshops_generate_report
    @workshop = Workshop.find_by_id(params[:workshop_id])
    
    if !@workshop.nil?
      @subgroups = Subgroup.all.each do |s|
        s.attendees.each do |a|
          a[:assisted] = AttendeeWorkshop.where("attendee_id = ? AND workshop_id = ?", a.id, params[:workshop_id]).any?
        end
      end
      render layout: false
    else
      render nothing: true
    end
  end

  def visits_to_exhibitors_by_exhibitor
    
    if params[:subgroup_id] =~ /\A\d+\z/
      @subgroup_id = params[:subgroup_id]
    end
    
  end

  def visits_to_exhibitors
    @attendees = []
    @subgroups = {}
    
    if params[:exhibitor_id] =~ /\A\d+\z/
      @attendees = Attendee.joins("INNER JOIN attendee_expositions a ON attendees.id = a.attendee_id")
      .where("a.exhibitor_id = ?", params[:exhibitor_id])
    elsif
      @attendees = Attendee.joins("INNER JOIN subgroups s ON attendees.subgroup_id = s.id")
      .joins("INNER JOIN attendee_expositions a ON attendees.id = a.attendee_id")
      .where("attendees.subgroup_id = ? AND a.exhibitor_id = ?", params[:subgroup_id], params[:exhibitor_id])
    end
    
    @attendees.each do |a|
      a[:register_date] = AttendeeExposition.find_by_attendee_id_and_exhibitor_id(a.id, params[:exhibitor_id]).created_at
      subgroup_name = a.subgroup.name
      
      if @subgroups.has_key?(subgroup_name)
        @subgroups[subgroup_name] << a
      else
        @subgroups[subgroup_name] = [a]
      end
      
    end
    
  end
  
  def visits_to_exhibitors_generate_report
    @exhibitor = Exhibitor.find_by_id(params[:exhibitor_id])
    
    if !@exhibitor.nil?
      
      @subgroups = Subgroup.all.each do |s|
        
        s.attendees.each do |a|
          a[:assisted] = AttendeeExposition.where("attendee_id = ? AND exhibitor_id = ?", a.id, params[:exhibitor_id]).any?
        end
        
        s.attendees.sort_by!{ |a| [(a[:assisted])? 0: 1, a.id] }
      end
      
      render layout: false
    else
      render nothing: true
    end
    
  end
  
  #  def control_numbers_report_html
  #    
  #  end
  
  def control_numbers_report_pdf
    pdf = Prawn::Document.new do
      @system_configuration = SystemConfiguration.first
      @attendees_total = Attendee.count
      @logo_url = "#{Rails.root}/public#{@system_configuration.logo.url.gsub(/\?.*\z/, "")}"
      image @logo_url, :height => 50
      text "EXPOMOBILE", :style => :bold, :size => 14, :align => :center;
      move_down 10
      text I18n.t("visit.control_numbers_report"), :style => :bold, :size => 12, :align => :center;
      move_down 50
      table_data_1 = [[I18n.t("visit.attendees_total"), @attendees_total], [I18n.t("visit.exhibitors_total"), Exhibitor.count], [I18n.t("visit.sponsors_total"), Sponsor.count], [I18n.t("visit.workshops_total"), Workshop.count]]
      table(table_data_1) do
        column(1).font_style = :bold
        self.cell_style = { :size => 7 }
      end
      move_down 20
      text I18n.t(:attendances), :style => :bold, :size => 10
      move_down 10
      table_data_2 = [[I18n.t(:exhibitors), "#{"%.1f" % (AttendeeExposition.count * 100 / @attendees_total)}%"], [I18n.t(:workshops), "#{"%.1f" % (AttendeeWorkshop.count * 100 / @attendees_total)}%"], [I18n.t("visit.users_using_the_app"), Nip.count]]
      table(table_data_2) do
        column(1).font_style = :bold
        self.cell_style = { :size => 7 }
      end
    end.render
    respond_to do |format|
      format.pdf {
        send_data pdf, filename: "control_numbers_report_#{Date.today.to_s.gsub("-", "_")}", type: "application/pdf", disposition: "inline"
      }
    end
  end
    
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/visits_to_exhibitors.html.erb
<% if @subgroups.blank? %>
  <h4><%= t(:no_visits) %></h4>
<% else %>
  <% @subgroups.keys.each do |k| %>
  <h3 style="margin-top: 50px;"><%= k %></h3>
    <div class="tab-content default-tab"> <!-- This is the target div. id must match the href of this div's tab -->
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th><%= t'atten.atten.name' %></th>
            <th><%= (t'exhibitor.social_reason').mb_chars.upcase %></th>
            <th><%= t'atten.atten.email' %></th>
            <th><%= t(:cellphone).upcase %></th>
            <th><%= t'atten.atten.main_line' %></th>
            <th><%= t(:register_date) %></th>
          </tr>

        </thead>

        <tbody>
          <% @subgroups[k].each do |a| %>
            <tr>
              <%if can? :show, Hour %>
                <td><%=link_to a.id, a, :class => 'button'%></td>
              <%else%>
                <td><%= label a.id, a.id %></td>
              <%end%>

              <td><%= a.a_name %></td>

              <td><%= a.e_name %></td>

              <td><%= a.a_email %></td>

              <td><%= a.a_cellphone %></td>

              <td><%= a.e_main_line %></td>

              <td><%= a.register_date %></td>
            <% end %>
        </tbody>
      </table>
    </div> 
  <% end %>
<% end %>

<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_exhibitors_by_exhibitor.html.erb
<div class="menu-links">
  <% Exhibitor.all.each do |e| %>
    <%= link_to e.name, visits_visits_to_exhibitors_path(:exhibitor_id => e.id, :subgroup_id => @subgroup_id), :class => "menu-link" %>
  <% end %>
</div>
<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_exhibitors_generate_report_by_exhibitor.html.erb
<div class="menu-links">
  <% Exhibitor.all.each do |e| %>
    <%= link_to e.name, visits_visits_to_exhibitors_generate_report_path(:exhibitor_id => e.id), :class => "menu-link" %>
  <% end %>
</div>

<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_exhibitors_index.html.erb
<script type="text/javascript">
  $(function() {
<% Group.all.each do |g| %>
    $("#pie_container_<%= g.id %>").highcharts({
    chart: {
    plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
    },
            title: {
    text: "<%= t("visit.total_visits_to_exhibitors_by_group") %>"
    },
            subtitle: {
    text: "<%= g.name %>"
    },
            tooltip: {
    pointFormat: "{series.name}: <b>{point.y}</b>"
    },
            plotOptions: {
    pie: {
    allowPointSelect: true,
            cursor: "pointer",
            dataLabels: {
    enabled: true,
            color: "#000000",
            connectorColor: "#000000",
            formatter: function() {
    if (this.y > 0) return "<b>" + this.point.name + "</b>: " + this.y;
    }
    }
    }
    },
  <% data = [] %>
  <% Exhibitor.all.each do |e| %>
    <% attendances = AttendeeExposition.joins("INNER JOIN exhibitors e ON attendee_expositions.exhibitor_id = e.id")
    .joins("INNER JOIN attendees a ON attendee_expositions.attendee_id = a.id")
    .joins("INNER JOIN subgroups s ON a.subgroup_id = s.id")
    .joins("INNER JOIN groups g ON s.group_id = g.id")
    .where("g.id = ? AND e.id = ?", g.id, e.id).count %>
    <% attendances = nil if attendances == 0 %>
    <% data << [e.name, attendances] %>
  <% end %>
    series: [{
    type: "pie",
            name: "<%= t(:attendances) %>",
            data: <%= data.to_json.html_safe %>
    }]
    });
            $("#bars_container_<%= g.id %>").highcharts({
    chart: {
    type: "bar"
    },
            title: {
    text: "<%= t("visit.visits_exhibitors_by_exhibitor") %>"
    },
            subtitle: {
    text: "<%= g.name %>"
    },
            xAxis: {
    categories: [
  <%= Exhibitor.all.map{ |e| "'#{e.name}'" }.join(",").html_safe %>
    ],
            allowDecimals: false
    },
            yAxis: {
    allowDecimals: false,
            title: {
    text: "<%= t(:visits) %>"
    }
    },
            tooltip: {
    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
    },
            plotOptions: {
    column: {
    pointPadding: 0.2,
            borderWidth: 0
    }
    },
  <% series = [] %>
  <% Subgroup.where(:group_id => g.id).order(:name).each do |s| %>
    <% data = [] %>
    <% Exhibitor.all.each do |e| %>
      <% attendances = AttendeeExposition.joins("INNER JOIN exhibitors e ON attendee_expositions.exhibitor_id = e.id")
      .joins("INNER JOIN attendees a ON attendee_expositions.attendee_id = a.id")
      .joins("INNER JOIN subgroups s ON a.subgroup_id = s.id")
      .where("s.id = ? AND e.id = ?", s.id, e.id).count %>
      <% attendances = nil if attendances == 0 %>
      <% data << attendances %>
    <% end %>
    <% series << { name: s.name, data: data } %>
  <% end %>
    series: <%= series.to_json.html_safe %>
    });
<% end %>
  });
</script>

<div class="menu-links">
  <%= link_to t("visit.visits_exhibitors_by_subgroup"), visits_visits_to_exhibitors_by_subgroup_path, :class => "menu-link" %>
  <%= link_to t("visit.visits_exhibitors_by_exhibitor"), visits_visits_to_exhibitors_by_exhibitor_path, :class => "menu-link" %>
  <%= link_to t(:generate_report), visits_visits_to_exhibitors_generate_report_by_exhibitor_path, :class => "menu-link" %>
</div>

<div id="pies_container" style="text-align: center; margin: 50px 0;">
  <% Group.all.each do |g| %>
    <div id="pie_container_<%= "#{g.id}" %>" style="min-width: 600px; min-height: 400px; margin: 0 25px; display: inline-block;"><%= g.name %></div>
  <% end %>
</div>

<% Group.all.each do |g| %>
  <div id="bars_container_<%= "#{g.id}" %>" style="min-width: 310px; min-height: 800px; margin: 50px auto;"><%= g.name %></div>
<% end %>

app/views/visits/visits_to_expositions.html.erb
<% if @subgroups.blank? %>
  <h4><%= t(:no_visits) %></h4>
<% else %>
  <% @subgroups.keys.each do |k| %>
  <h3 style="margin-top: 50px;"><%= k %></h3>
    <div class="tab-content default-tab"> <!-- This is the target div. id must match the href of this div's tab -->
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th><%= t'atten.atten.name' %></th>
            <th><%= (t'exhibitor.social_reason').mb_chars.upcase %></th>
            <th><%= t'atten.atten.email' %></th>
            <th><%= t(:cellphone).upcase %></th>
            <th><%= t'atten.atten.main_line' %></th>
            <th><%= t(:register_date) %></th>
          </tr>

        </thead>

        <tbody>
          <% @subgroups[k].each do |a| %>
            <tr>
              <%if can? :show, Hour %>
                <td><%=link_to a.id, a, :class => 'button'%></td>
              <%else%>
                <td><%= label a.id, a.id %></td>
              <%end%>

              <td><%= a.a_name %></td>

              <td><%= a.e_name %></td>

              <td><%= a.a_email %></td>

              <td><%= a.a_cellphone %></td>

              <td><%= a.e_main_line %></td>

              <td><%= a.register_date %></td>
            <% end %>
        </tbody>
      </table>
    </div> 
  <% end %>
<% end %>

<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_expositions_by_exposition.html.erb
<div class="menu-links">
  <% Exposition.all.each do |e| %>
    <%= link_to e.name, visits_visits_to_expositions_path(:exposition_id => e.id, :subgroup_id => @subgroup_id), :class => "menu-link" %>
  <% end %>
</div>
<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_expositions_by_subgroup.html.erb
<% Group.all.each do |g| %>
  <% @group_id = g.id %>
  <div class="group-container">
    <h3><%= g.name %></h3>
    <% Subgroup.where("group_id = ?", @group_id).each do |s| %>
      <%= link_to "#{s.name} #{s.subgroup_key}", visits_visits_to_expositions_by_exposition_path(:subgroup_id => s.id), :class => "menu-link" %>
    <% end %>
  </div>
<% end %>
<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_expositions_generate_report_by_exposition.html.erb
<div class="menu-links">
  <% Exposition.all.each do |e| %>
    <%= link_to e.name, visits_visits_to_expositions_generate_report_path(:exposition_id => e.id), :class => "menu-link" %>
  <% end %>
</div>

<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_expositions_index.html.erb
<script type="text/javascript">
  $(function() {
<% Group.all.each do |g| %>
    $('#container_<%= g.id %>').highcharts({
    chart: {
    type: 'bar'
    },
            title: {
    text: "<%= t("visit.visits_expositions_by_exposition") %>"
    },
            subtitle: {
    text: "<%= g.name %>"
    },
            xAxis: {
    categories: [
  <%= Exhibitor.all.map{ |e| "'#{e.name}'" }.join(",").html_safe %>
    ],
            allowDecimals: false
    },
            yAxis: {
    allowDecimals: false,
            title: {
    text: "<%= t(:visits) %>"
    }
    },
            tooltip: {
    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
    },
            plotOptions: {
    column: {
    pointPadding: 0.2,
            borderWidth: 0
    }
    },
  <% series = [] %>
  <% Subgroup.where(:group_id => g.id).order(:name).each do |s| %>
    <% data = [] %>
    <% Exhibitor.all.each do |e| %>
      <% attendances = AttendeeExposition.joins("INNER JOIN exhibitors e ON attendee_expositions.exhibitor_id = e.id")
      .joins("INNER JOIN attendees a ON attendee_expositions.attendee_id = a.id")
      .joins("INNER JOIN subgroups s ON a.subgroup_id = s.id")
      .where("s.id = ? AND e.id = ?", s.id, e.id).count %>
      <% attendances = nil if attendances == 0 %>
      <% data << attendances %>
    <% end %>
    <% series << { name: s.name, data: data } %>
  <% end %>
    series: <%= series.to_json.html_safe %>
    });
<% end %>
  });
</script>

<div class="menu-links">
  <%= link_to t("visit.visits_expositions_by_subgroup"), visits_visits_to_expositions_by_subgroup_path, :class => "menu-link" %>
  <%= link_to t("visit.visits_expositions_by_exposition"), visits_visits_to_expositions_by_exposition_path, :class => "menu-link" %>
  <%= link_to t(:generate_report), visits_visits_to_expositions_generate_report_by_exposition_path, :class => "menu-link" %>
</div>

<% Group.all.each do |g| %>
  <div id="container_<%= "#{g.id}" %>" style="min-width: 310px; min-height: 800px; margin: 50px auto;"><%= g.name %></div>
<% end %>

app/views/visits/visits_to_workshops_by_subgroup.html.erb
<% Group.all.each do |g| %>
  <% @group_id = g.id %>
  <div class="group-container">
    <h3><%= g.name %></h3>
    <% Subgroup.where("group_id = ?", @group_id).each do |s| %>
      <%= link_to "#{s.name} #{s.subgroup_key}", visits_visits_to_workshops_by_workshop_path(:subgroup_id => s.id), :class => "menu-link" %>
    <% end %>
  </div>
<% end %>

<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_workshops_generate_report_by_workshop.html.erb
<div class="menu-links">
  <% Workshop.all.each do |w| %>
    <%= link_to w.name, visits_visits_to_workshops_generate_report_path(:workshop_id => w.id), :class => "menu-link" %>
  <% end %>
</div>

<div style="text-align: center; margin-top: 50px;">
  <%= link_to t(:back), :back, :class => "button", :style => "width: 100px; height: 25px; font-size: 20px !important; text-align: center;" %>
</div>

app/views/visits/visits_to_workshops_index.html.erb
<script type="text/javascript">
  $(function() {
<% Group.all.each do |g| %>
    var total = 0;
            $("#pie_container_<%= g.id %>").highcharts({
    chart: {
    plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
    },
            title: {
    text: "<%= t("visit.total_visits_to_workshops_by_group") %>"
    },
            subtitle: {
    text: "<%= g.name %>"
    },
            tooltip: {
    pointFormat: "{series.name}: <b>{point.y}</b>"
    },
            plotOptions: {
    pie: {
    allowPointSelect: true,
            cursor: "pointer",
            dataLabels: {
    enabled: true,
            color: "#000000",
            connectorColor: "#000000",
            formatter: function() {
    if (this.y > 0) return "<b>" + this.point.name + "</b>: " + this.y;
    }
    }
    }
    },
  <% data = [] %>
  <% Workshop.all.each do |w| %>
    <% attendances = AttendeeWorkshop.joins("INNER JOIN workshops w ON attendee_workshops.workshop_id = w.id")
    .joins("INNER JOIN attendees a ON attendee_workshops.attendee_id = a.id")
    .joins("INNER JOIN subgroups s ON a.subgroup_id = s.id")
    .joins("INNER JOIN groups g ON s.group_id = g.id")
    .where("g.id = ? AND w.id = ?", g.id, w.id).count %>
    <% attendances = nil if attendances == 0 %>
    <% data << [w.name, attendances] %>
  <% end %>
    series: [{
    type: "pie",
            name: "<%= t(:attendances) %>",
            data: <%= data.to_json.html_safe %>
    }]
    });
            $('#bars_container_<%= g.id %>').highcharts({
    chart: {
    type: 'bar'
    },
            title: {
    text: "<%= t("visit.visits_workshops_by_workshop") %>"
    },
            subtitle: {
    text: "<%= g.name %>"
    },
            xAxis: {
    categories: [
  <%= Workshop.all.map{ |w| "'#{w.name}'" }.join(",").html_safe %>
    ],
            allowDecimals: false
    },
            yAxis: {
    allowDecimals: false,
            title: {
    text: "<%= t(:visits) %>"
    }
    },
            tooltip: {
    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
    },
            plotOptions: {
    column: {
    pointPadding: 0.2,
            borderWidth: 0
    },
    },
  <% series = [] %>
  <% Subgroup.where(:group_id => g.id).order(:name).each do |s| %>
    <% data = [] %>
    <% Workshop.all.each do |w| %>
      <% attendances = AttendeeWorkshop.joins("INNER JOIN workshops w ON attendee_workshops.workshop_id = w.id")
      .joins("INNER JOIN attendees a ON attendee_workshops.attendee_id = a.id")
      .joins("INNER JOIN subgroups s ON a.subgroup_id = s.id")
      .where("s.id = ? AND w.id = ?", s.id, w.id).count %>
      <% attendances = nil if attendances == 0 %>
      <% data << attendances %>
    <% end %>
    <% series << { name: s.name, data: data } %>
  <% end %>
    series: <%= series.to_json.html_safe %>
    });
<% end %>
  });
</script>

<div class="menu-links">
  <%= link_to t("visit.visits_workshops_by_subgroup"), visits_visits_to_workshops_by_subgroup_path, :class => "menu-link" %>
  <%= link_to t("visit.visits_workshops_by_workshop"), visits_visits_to_workshops_by_workshop_path, :class => "menu-link" %>
  <%= link_to t(:generate_report), visits_visits_to_workshops_generate_report_by_workshop_path, :class => "menu-link" %>
</div>

<div id="pies_container" style="text-align: center; margin: 50px 0;">
  <% Group.all.each do |g| %>
    <div id="pie_container_<%= "#{g.id}" %>" style="min-width: 600px; min-height: 400px; margin: 0 25px; display: inline-block;"><%= g.name %></div>
  <% end %>
</div>

<% Group.all.each do |g| %>
  <div id="bars_container_<%= "#{g.id}" %>" style="min-width: 310px; min-height: 800px; margin: 50px auto;"><%= g.name %></div>
<% end %>