config/routes.rb
Expomobile::Application.routes.draw do

  resources :massive_loads

  resources :system_configurations

  get "rating/show_rating"

  resources :diaries
  
  get "face_to_faces/generate_diary"
  get "face_to_faces/get_interviewee"
  resources :face_to_faces

  resources :activities

  resources :conferences

  get "qr_generator/generate_qr"
 
  resources :sponsors

  post "workshops/set_tolerance"
  get "visits/visits_to_workshops_index"
  get "visits/visits_to_exhibitors_index"
  get "visits/visits_to_workshops_by_subgroup"
  get "visits/visits_to_workshops_by_workshop"
  get "visits/visits_to_exhibitors_by_subgroup"
  get "visits/visits_to_exhibitors_by_exhibitor"
  get "visits/visits_to_workshops"
  get "visits/visits_to_exhibitors"
  get "visits/visits_to_workshops_generate_report"
  get "visits/visits_to_exhibitors_generate_report"
  get "visits/visits_to_workshops_generate_report_by_workshop"
  get "visits/visits_to_exhibitors_generate_report_by_exhibitor"
  get "visits/control_numbers_report_html"
  get "visits/control_numbers_report_pdf"

  resources :expositions
  
  get "mobile_services/rate"
  get "mobile_services/index_diary_days"
  get "mobile_services/show_diary"
  get "mobile_services/index_diaries"
  get "mobile_services/index_face_to_face_days"
  get "mobile_services/show_face_to_face"
  get "mobile_services/index_face_to_faces"
  get "mobile_services/index_activity_days"
  get "mobile_services/show_activity"
  get "mobile_services/index_activities"
  get "mobile_services/index_conference_days"
  get "mobile_services/show_conference"
  get "mobile_services/index_conferences"
  get "mobile_services/show_sponsor"
  get "mobile_services/index_sponsors"
  get "mobile_services/get_attendee_id"
  get "mobile_services/get_attendee_nip"
  get "mobile_services/index_offerts"
  get "mobile_services/show_offert"
  get "mobile_services/index_exhibitors"
  get "mobile_services/show_exhibitor"  
  get "mobile_services/index_workshop_days"
  get "mobile_services/index_exposition_days"
  get "mobile_services/index_workshops"
  get "mobile_services/index_expositions"
  get "mobile_services/index_expositions_names"
  get "mobile_services/register_visit_to_workshop"
  get "mobile_services/register_visit_to_exposition"
  
  resources :hours

  resources :subgroups
  
  get "schedules/subgroup_change"
  post "schedules/deallocate"
  post "schedules/do_association"
  get "schedules/associate_workshop_group"

  resources :rooms

  resources :workshops

  resources :groups

  resources :offerts

  resources :exhibitors
  
  match "register" => "attendees#register"
  match "register_attendee" => "attendees#register_attendee"
  get "attendees/print_gafete_c"
  get "attendees/print_gafete_b"
  get "attendees/print_gafete_a"
  get "attendees/generate_gafete"
  get "attendees/get_all_attendee_names"
  get "attendees/get_attendee_by_name"
  get "attendees/get_attendee"
  resources :attendees

  get "welcome/index"

  devise_for :users

  resources :users

  devise_scope :user do
    get "devise/sessions/sing_out" => "devise/sessions#destroy", :as => :destroy_user_session
    get "devise/sessions/links" => "devise/sessions#links", :as => :links
    match 'devise/registrations/:id/edit' => 'devise/registrations#edit', :as => :edit_user
  end

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :attendee_id, :a_cellphone, :a_chat, :a_email, :a_is_director, :a_market_segment, :a_name, :a_num_employees, :a_other_line, :a_platform, :a_radio_nextel, :a_sec_line, :a_tel_nextel, :a_web, :e_city, :e_colony, :e_ext_number, :e_int_number, :e_lada, :e_main_line, :e_municipality, :e_name, :e_phone, :e_rfc, :e_state, :e_street, :e_tradename, :e_zip_code, :subgroup_id
  has_one :nip, :dependent => :destroy
  belongs_to :subgroup
  has_many :schedules, :through => :subgroup
  has_many :hours, :through => :schedules
  has_many :workshops, :through => :schedules
  
  validates :a_cellphone, :a_email, :a_market_segment, :a_name, :a_num_employees, :a_platform, :e_city, :e_colony, :e_ext_number, :e_lada, :e_municipality, :e_name, :e_phone, :e_rfc, :e_state, :e_street, :e_tradename, :e_zip_code, :presence => true
  validates_numericality_of :a_num_employees, :if => :a_num_employees
  validates_numericality_of :e_ext_number, :if => :e_ext_number
  validates_numericality_of :e_zip_code, :if => :e_zip_code
  validates_numericality_of :e_lada, :if => :e_lada
  validates_format_of :attendee_id, :with => /\A[A-Z]\d{3}\z/, :if => :attendee_id
end

app/controllers/attendees_controller.rb
# encoding: utf-8

class AttendeesController < ApplicationController
  before_filter :authenticate_user!, :except => [:register, :register_attendee]

  def index
    if params[:search].blank?
      @attendees = Attendee.order('id DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @attendees = Attendee.where("a_name LIKE '%#{params[:search]}%'").order('id DESC').paginate(:per_page => 10, :page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendees }
    end
  end

  # GET /attendees/1
  # GET /attendees/1.json
  def show
    @attendee = Attendee.find(params[:id])
    @workshops = Workshop.joins("INNER JOIN attendee_workshops a ON workshops.id = a.workshop_id")
    .joins("INNER JOIN attendees at ON a.attendee_id = at.id")
    .where("at.id = ?", @attendee.id)
    @expositions = Exposition.joins("INNER JOIN attendee_expositions a ON expositions.id = a.exhibitor_id")
    .joins("INNER JOIN attendees at ON a.attendee_id = at.id")
    .where("at.id = ?", @attendee.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.json
  def new
    @attendee = Attendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
  end

  # POST /attendees
  # POST /attendees.json
  def create
    unless params[:attendee][:e_city].blank?
      params[:attendee][:attendee_id] = (params[:attendee][:e_city][0].upcase + Array.new(2){[*'0'..'9'].sample}.join + ["0", "2", "4", "6", "8"].sample)
      while !Attendee.find_by_attendee_id(params[:attendee][:attendee_id]).nil?
        params[:attendee][:attendee_id] = (params[:attendee][:e_city][0].upcase + Array.new(2){[*'0'..'9'].sample}.join + ["0", "2", "4", "6", "8"].sample)
      end
    end
    params[:attendee][:a_platform] = params[:attendee][:a_platform].join(";") unless params[:attendee][:a_platform].nil?
    params[:attendee][:a_market_segment] = params[:attendee][:a_market_segment].join(";") unless params[:attendee][:a_market_segment].nil?
    @attendee = Attendee.new(params[:attendee])

    respond_to do |format|
      if @attendee.save
        format.html { redirect_to @attendee, notice: t(:successfully_created) }
        format.json { render json: @attendee, status: :created, location: @attendee }
      else
        format.html { render action: "new" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.json
  def update
    @attendee = Attendee.find(params[:id])
    params[:attendee][:a_platform] = (params[:attendee][:a_platform] & ["Blackberry", "IPhone", "Android"]) if params[:other_platform].nil?
    params[:attendee][:a_platform] = params[:attendee][:a_platform].join(";") unless params[:attendee][:a_platform].nil?
    params[:attendee][:a_market_segment] = (params[:attendee][:a_market_segment] & ["Gobierno", "Corporativo", "PyMEs", "Educación", "Salud", "Retail", "Web"]) if params[:other_market].nil?
    params[:attendee][:a_market_segment] = params[:attendee][:a_market_segment].join(";") unless params[:attendee][:a_market_segment].nil?
    
    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
        format.html { redirect_to @attendee, notice: t(:successfully_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.json
  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to attendees_url }
      format.json { head :no_content }
    end
  end
  
  def get_id

    if params[:attendee_id] =~ /^[A-Z]\d{3}$/
      @attendee = Attendee.find_by_attendee_id(params[:attendee_id])
      
      if !@attendee.nil?
        @attendee_id = @attendee.id
        @nip = Nip.find_by_attendee_id(@attendee_id)
      
        while @nip.nil?
          random_value = Array.new(4){[*'0'..'9', *'a'..'z'].sample}.join
          @exists = Nip.find_by_nip(random_value)
        
          if @exists.nil?
            @nip = Nip.create(:nip => random_value)
            @nip.attendee_id = @attendee_id
          end
        end
      
        @times_sent = (@nip.times_sent.nil?) ? 0: @nip.times_sent
      
        if @times_sent < 10
          @can_send_email = false
          @can_send_email = ((Time.now - @nip.sent) >= 0) unless @nip.sent.nil?
      
          if @nip.sent.nil? || @can_send_email
            @email = @attendee.a_email
            @domain = @email.gsub(/@.*$/, "")
    
            
            if !@attendee.email.nil?
              
              if AttendeeMailer.send_nip(@attendee, @nip).deliver!
                @nip.update_attributes(:sent => Time.now, :times_sent => (@nip.times_sent.nil?) ? 1: @nip.times_sent += 1 )
                @msg = { email: @email, domain: @domain, msg: t("atten.nip_sended", :email => @email), sent: "ok" }
              else
                @msg = { email: @email, domain: @domain, msg: t("errors.atten_email_dont_sended"), sent: "no" }
              end
            
            else
              @msg = { email: @email, domain: @domain, msg: t("errors.atten_email_not_registered"), sent: "no" }
            end
      
          else
            @msg = { email: @email, domain: @domain, msg: t("errors.atten_email_already_sended"), sent: "no" }
          end
        
        else
          @msg = { email: @email, domain: @domain, msg: t("errors.atten_email_maximum_sends"), sent: "no" }
        end
    
      else
        @msg = { email: nil, domain: nil, msg: t("errors.atten_not_exists"), sent: "no" }
      end
      
    else
      @msg = { email: nil, domain: nil, msg: t("errors.atten_invalid_id"), sent: "no" }
    end
    
    respond_to do |format|
      format.json { render json: @msg }
    end
  end
  
  def get_nip
    
    if params[:attendee_id] =~ /^[A-Z]\d{3}$/
      @attendee = Attendee.find_by_attendee_id(params[:attendee_id])
      
      if !@attendee.nil?
        @attendee_id = @attendee.id
        if params[:nip] =~ /^[0-9a-z]{4}$/
          @nip = @attendee.nip
          @email = @attendee.a_email
      
          if params[:nip] == @nip.nip
            @msg = { access: "ok", email: @email, msg: t("atten.access_ok") }
            session[:attendee_id] = @attendee_id
          else
            @msg = { access: "no", email: @email, msg: t("errors.atten_nips_dont_match") }
          end
      
        else
          @msg = { access: "no", email: @email, msg: t("errors.atten_invalid_nip") }
        end
      
      else
        @msg = { email: nil, domain: nil, msg: t("errors.atten_not_exists"), sent: "no" }
      end
      
    else
      @msg = { access: "no", email: @email, msg: t("errors.atten_invalid_id") }
    end

    respond_to do |format|
      format.json { render json: @msg }
    end
  end
  
  def get_attendee
    @attendee = Attendee.where(:attendee_id => params[:attendee_id].upcase).select([:id, :a_name, :e_name, :a_email, :e_phone]).first
    
    render json: @attendee
  end
  
  def get_attendee_by_name
    @attendee = Attendee.where(:a_name => params[:a_name].upcase).select([:id, :attendee_id, :e_name, :a_email, :e_phone]).first
    
    render json: @attendee
  end
  
  def get_all_attendee_names
    @attendees = Attendee.uniq.pluck(:a_name)
    
    render json: @attendees
  end
  
  def generate_gafete
    @attendee_id = params[:attendee_id]
    @a_name = params[:a_name]
    @conferences = Conference.order(:start_date).limit(5)
    @diaries = Diary.order(:event_date).limit(5)
    @e_tradename = params[:e_tradename]
    @e_phone = params[:e_phone]
    @a_email = params[:a_email]
    @e_address = params[:e_address]
    @a_web = params[:a_web]
    @system_configuration = SystemConfiguration.first
  end
  
  def print_gafete_a
    @a_name = params[:a_name]
    @e_tradename = params[:e_tradename]
    @e_phone = params[:e_phone]
    @a_email = params[:a_email]
    @e_address = params[:e_address]
    @a_web = params[:a_web]
    @with_logos = params[:with_logos]
    @system_configuration = SystemConfiguration.first
    render layout: false
  end
  
  def print_gafete_b
    @offset = params[:offset]
    @conferences = Conference.order(:start_date).limit(5).offset(@offset)
    @with_logos = params[:with_logos]
    @system_configuration = SystemConfiguration.first
    render layout: false
  end
  
  def print_gafete_c
    @offset = params[:offset]
    @diaries = Diary.order(:event_date).limit(5).offset(@offset)
    @with_logos = params[:with_logos]
    @system_configuration = SystemConfiguration.first
    render layout: false
  end
  
  def register
    @attendee = Attendee.new
    render layout: "register_attendee"
  end
  
  def register_attendee
    unless params[:attendee][:e_city].blank?
      params[:attendee][:attendee_id] = (params[:attendee][:e_city][0].upcase + Array.new(2){[*'0'..'9'].sample}.join + ["0", "2", "4", "6", "8"].sample)
      while !Attendee.find_by_attendee_id(params[:attendee][:attendee_id]).nil?
        params[:attendee][:attendee_id] = (params[:attendee][:e_city][0].upcase + Array.new(2){[*'0'..'9'].sample}.join + ["0", "2", "4", "6", "8"].sample)
      end
    end
    params[:attendee][:a_platform] = params[:attendee][:a_platform].join(";") unless params[:attendee][:a_platform].nil?
    params[:attendee][:a_market_segment] = params[:attendee][:a_market_segment].join(";") unless params[:attendee][:a_market_segment].nil?
    @attendee = Attendee.new(params[:attendee])

    respond_to do |format|
      if @attendee.save

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/generate_gafete.html.erb
<script type="text/javascript">
  $(function() {
    $("#with_logos").change(function() {
      if ($(this).prop("checked")) {
        $(".gafete-logo").css({visibility: "visible"});
        $("#gafete-text").css({"border-top": "1px solid #000", "border-bottom": "1px solid #000", "padding-top": "0"});
        $(".generate-gafete").each(function() {
          var generate_gafete_href = $(this).attr("href").replace("&with_logos=false", "&with_logos=true");
          $(this).attr("href", generate_gafete_href);
        });
      }
      else {
        $(".gafete-logo").css({visibility: "hidden"});
        $("#gafete-text").css({border: "none", "padding-top": "1px"});
        $(".generate-gafete").each(function() {
          var generate_gafete_href = $(this).attr("href").replace("&with_logos=true", "&with_logos=false");
          $(this).attr("href", generate_gafete_href);
        });
      }
    });

    $("#with_conferences").change(function() {
      if ($(this).prop("checked")) {
        $("#conferences").show();
      }
      else {
        $("#conferences").hide();
      }
    });

    $("#with_diary").change(function() {
      if ($(this).prop("checked")) {
        $("#diary").show();
      }
      else {
        $("#diary").hide();
      }
    });
  });
</script>
<h2 style="text-align: center; margin-bottom: 20px;"><%= "#{t("atten.generate_gafete")} gafete" %></h2>
<%= label_tag t("atten.with_logos"), nil, :style => "font-size: 14px; font-weight: bold; color: #000;" %>
<%= check_box_tag "with_logos", nil, true, :style => "margin-right: 15px;" %>
<%= label_tag t("atten.with_conferences"), nil, :style => "font-size: 14px; font-weight: bold; color: #000;" %>
<%= check_box_tag "with_conferences", nil, true, :style => "margin-right: 15px;" %>
<%= label_tag t("atten.with_diary"), nil, :style => "font-size: 14px; font-weight: bold; color: #000;" %>
<%= check_box_tag "with_diary", nil, true, :style => "margin-right: 15px;" %>
<div style="margin: 15px 0px; font-size: 14px; color: #000;">
  <span style="font-weight: bold;"><%= t(:note) %>:</span><span> <%= t(:gafete_note) %>.</span>
</div>
<% @logo_url = @system_configuration.logo.url %>
<% @banner_url = @system_configuration.banner.url %>
<div id="gafete" style="width: 305px; height: 415px; margin: 0 auto 30px; border: 1px solid #000; color: #000;">
  <div class="gafete-logo" style="height: 85px; width: 305px; border-bottom: 1px solid #000; visibility: visible;">
    <%= image_tag @logo_url, :height => 70, :style => "height: 65px; -ms-interpolation-mode: bicubic; margin: 7px; display: inline-block;" %>
    <%#= image_tag "https://chart.googleapis.com/chart?cht=qr&chs=#{85}x#{85}&chl=[#{@a_name},#{@e_tradename},WORK:#{@e_phone},#{@a_email},#{@e_address},#{@a_web}]", :style => "margin: 0px; float: right;" %>    
  </div>
  <div class="gafete-logo" style="height: 135px; width: 305px; text-align: center; visibility: visible;">
    <%= image_tag @banner_url, :height => 125, :width => 295, :style => "height: 125px; width: 290px; -ms-interpolation-mode: bicubic; margin: 5px;" %>
  </div>
  <div id="gafete-text" style="height: 115px; border-top: 1px solid #000; border-bottom: 1px solid #000; line-height: 20px; font-family: Arial, Helvetica, sans-serif; text-align: center;">
    <span style="font-weight: bold; font-size: 16px; top: 15px; position: relative; display: block; height: 40px; margin: 0px 10px;"><%= @a_name %></span>
    <span style="font-size: 16px; top: 20px; position: relative; margin: 0px 10px;"><%= @e_tradename %></span>
  </div>
  <div class="gafete-logo" style="height: 80px; width: 305px; visibility: visible;">
    <%#= image_tag "/assets/logoexpo.png", :width => 100, :style => "width 140px; height: auto; -ms-interpolation-mode: bicubic; top: 8px; position: relative;" %>
    <div style="float: right; display: inline-block; padding: 20px 20px 0 0; font-family: Arial, Helvetica, sans-serif; font-size: 12px;">
      <%= image_tag "/assets/face48.png", :width => 20, :style => "width 20px; height: auto; -ms-interpolation-mode: bicubic;" %>
      <span style="position: relative; bottom: 5px;">vinculotic</span><br/>
      <%= image_tag "/assets/tweet48.png", :width => 20, :style => "width 20px; height: auto; -ms-interpolation-mode: bicubic;" %>
      <span style="position: relative; bottom: 5px;">@vinculotic</span>
    </div>
  </div>
</div>
<div id="buttons" style="width: 290px; margin: 0 auto 30px; text-align: center;">
  <%= link_to t("atten.print_gafete"), attendees_print_gafete_a_path(:a_name => @a_name, :e_tradename => @e_tradename, :e_phone => @e_phone, :a_email => @a_email, :e_address => @e_address, :a_web => @a_web, :with_logos => "true"), :class => "button generate-gafete", :target => "_blank" %>
</div>
<div id="conferences">
  <h3 style="margin-bottom: 20px;"><%= t(:conferences) %></h3>
  <% @offset = 0 %>
  <% until @conferences.blank? %>
    <div style="display: inline-block; margin: 0 30px;">
      <div style="width: 305px; height: 415px; margin-bottom: 30px; border: 1px solid #000; padding: 0 20px; font-family: Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1; color: #000;">
        <div class="gafete-logo" style="height: 85px; visibility: visible;">
          <%= image_tag @logo_url, :height => 70, :style => "height: 65px; -ms-interpolation-mode: bicubic; margin: 7px;" %>
        </div>
        <% @conferences.each do |conference| %>
          <div class="conference" style="padding: 10px 0px; border-bottom: 1px solid #aaa; font-size: 10px; vertical-align: top;">
            <div class="hour" style="display: inline-block; width: 70px; font-size: 8px;"><%= "#{conference.start_date.strftime("%I:%M%p")} - #{conference.end_date.strftime("%I:%M%p")}" %></div>
            <div class="conferencist-photo" style="width: 40px; display: inline-block;">
              <% if conference.photo.url(:thumb) != "/assets/missing.jpg" %>
                <%= image_tag conference.photo.url(:thumb), :width => 40, :style => "width: 40px; -ms-interpolation-mode: bicubic;" %>
              <% end %>
            </div>
            <div class="conference-details" style="width: 150px; padding-left: 10px; display: inline-block;">
              <span style="font-weight: bold;"><%= conference.name %></span><br/>
              <span style="color: #c00205;"><%= conference.conferencist %></span>
            </div>
          </div>
        <% end %>
      </div>
      <div id="buttons" style="width: 290px; margin: 0 auto 30px; text-align: center;">
        <%= link_to t("atten.print_gafete"), attendees_print_gafete_b_path(:offset => @offset, :with_logos => "true"), :class => "button generate-gafete", :target => "_blank" %>
      </div>
    </div>
    <% @offset += 5 %>
    <% @conferences = Conference.limit(5).offset(@offset) %>
  <% end %>
</div>
<div id="diary">
  <h3 style="margin-bottom: 20px;"><%= t("activerecord.models.diary").capitalize %></h3>
  <% @offset = 0 %>
  <% until @diaries.blank? %>
    <div style="display: inline-block; margin: 0 30px;">
      <div style="width: 305px; height: 415px; margin-bottom: 30px; border: 1px solid #000; padding: 0 20px; font-family: Arial, Helvetica, sans-serif; font-size: 12px; line-height: 1; color: #000;">
        <div class="gafete-logo" style="height: 85px; visibility: visible;">
          <%= image_tag @logo_url, :height => 70, :style => "height: 65px; -ms-interpolation-mode: bicubic; margin: 7px;" %>
        </div>
        <% @diaries.each do |diary| %>
          <div class="diary" style="padding: 10px 0px; border-bottom: 1px solid #aaa; font-size: 10px; vertical-align: top;">
            <div class="hour" style="display: inline-block; width: 70px; font-size: 8px;"><%= "#{diary.event_date.strftime("%I:%M%p")} - #{diary.event_end_date.strftime("%I:%M%p")}" %></div>
            <div class="diary-details" style="width: 150px; padding-left: 10px; display: inline-block;">
              <span style="font-weight: bold;"><%= diary.description %></span><br/>
              <span style="color: #c00205;"><%= diary.place %></span>
            </div>
          </div>
        <% end %>
      </div>
      <div id="buttons" style="width: 290px; margin: 0 auto 30px; text-align: center;">
        <%= link_to t("atten.print_gafete"), attendees_print_gafete_c_path(:offset => @offset, :with_logos => "true"), :class => "button generate-gafete", :target => "_blank" %>
      </div>
    </div>
    <% @offset += 5 %>
    <% @diaries = Diary.limit(5).offset(@offset) %>
  <% end %>
</div>

app/views/attendees/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "attendees" %>
<% end %>

<div style="margin: 25px">
  <%= form_tag attendees_path, :method => "get", :id => "search_form" do %>
    <%= label_tag t(:search_by_name) %>
    <%= text_field_tag :search, params[:search], :id => "search_field", :class => "text-input small-input", :style => "margin-right: 10px;" %>
  <% end %>
</div>
<div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab -->
  <table>
    <thead>
      <tr>
<%#*<th><input class="check-all" type="checkbox" /></th>%>
        <th>ID</th>
        <th><%= t'atten.atten.register_id' %></th>
        <th><%= t'atten.atten.subgroup' %></th>
        <th><%= t'atten.enter.tradename' %></th>
        <th><%= t'atten.atten.name' %></th>
        <th><%= (t'atten.gafete').upcase %></th>
        <th><%= t'atten.atten.email' %></th>
        <th><%= t'atten.atten.cellphone' %></th>
        <th><%= t'atten.atten.is_director' %></th>
        <th><%= t'atten.atten.platform' %></th>
      </tr>

    </thead>

    <tfoot>
      <tr>
        <td colspan="13">
<%#*<div class="bulk-actions align-left">%>
<%#= render "layouts/select_action" %>
<%#*</div>%>
          <%= render "layouts/pagination" %>
          <div class="clear"></div>
        </td>
      </tr>
    </tfoot>

    <tbody>
      <% @attendees.each do |attendee| %>
        <tr>
  <%#*<td><input type="checkbox" /></td>%>
  <%#if can? :show, Attendee %>
  <%#*<td><%=link_to attendee.id, attendee, :class => 'button'</td>%>
  <%#else%>
          <td><%= label attendee.id, attendee.id %></td>
  <%#end%>
          <% @model = attendee %>
          <td><%= attendee.attendee_id %></td>

          <td><%= attendee.subgroup.name %></td>

          <td><%= attendee.e_tradename %></td>                      

          <td><%= attendee.a_name %></td>

          <td><%= link_to t("atten.generate_gafete"), attendees_generate_gafete_path(
              :attendee_id => attendee.attendee_id, :a_name => attendee.a_name, :e_tradename => attendee.e_tradename, :e_phone => attendee.e_phone, 
              :a_email => attendee.a_email, :e_address => "#{attendee.e_street} #{attendee.e_ext_number}, #{attendee.e_colony}", 
              :a_web => attendee.a_web, :layout => "true"
              ), :class => "button" %></td>

          <td><%= attendee.a_email %></td>            

          <td><%= attendee.a_cellphone %></td> 

          <td><%= t("#{attendee.a_is_director.to_s}_value") %></td>

          <td><%= (attendee.a_platform.nil?)? "": attendee.a_platform.gsub(";", "; ").gsub(/;\s$/, "") %></td>

          <%= render "layouts/index_links" %>
        <% end %>
    </tbody>
  </table>
  <%= render "layouts/action_links" %>
</div> 
<%= render "layouts/second_tab" %>